### ISSUE TITLE
Seek in audio player

### ISSUE THREAD

**Issue by knownasilya** [ember-weekend/ember-weekend#1]
Being able to jump anywhere in the podcast would be very useful!

**Comment by rondale-sc** [comment]
@knownasilya We have design for this!  I'm really excited to see it work, we'll hopefully get it on the site in the next week or so.  Shouldn't be too hard, just a matter of putting the time in.  :+1:

**Comment by knownasilya** [comment]
Sweet!

**Comment by rondale-sc** [comment]
Yay! :beers:
