### ISSUE TITLE
Move to a FastBoot server

### ISSUE THREAD

**Issue by code0100fun** [ember-weekend/ember-weekend#2]
Possibly change deployment to Heroku?

**Comment by rondale-sc** [comment]
Until this: https://github.com/emberjs/ember.js/issues/11115 is resolve we likely will be unable to continue down this path.  

Looks like it'll be worked on soon though, so that's awesome!

**Comment by Dhaulagiri** [comment]
Seems like you guys were able to figure this out without too much trouble.  I'd love to hear more, either here or on the show, about how easy or hard you found it to get FastBoot working with the site?  I have had mixed results trying to get projects working with FastBoot.

**Comment by rondale-sc** [comment]
@Dhaulagiri We'll definitely cover it soon.  There were a few hurdles, but all in all it was a great experience.  

You can check out the initial implementation here: ember-weekend.herokuapp.com

**Comment by rondale-sc** [comment]
Ember Weekend is now on a FB server! :)
