### ISSUE TITLE
hard refresh of detail route acts differently than navigation from the list view

### ISSUE THREAD

**Issue by toranb** [ember-weekend/ember-weekend#37]
https://emberweekend.com/episodes/adventures-in-the-amazon

When I tried to navigate (in firefox/chrome) to the url above from the root page I noticed only the player loads. Yet if I "hard refresh" from that url (detail route) I get all the details

Is this a bug or the intended behavior ?

Love the show -keep up the great work :)

**Comment by rondale-sc** [comment]
@toranb Thanks for reporting.  This should be fixed in: https://github.com/ember-weekend/ember-weekend/commit/3c9424573847e49b7ffbb138d33c2bc3b68ce5d5

Thought it won't be deploy for a few more minutes (lunch-ish time)

**Comment by rondale-sc** [comment]
We are using slug as an id (basically).  you can see how this is working here:

https://github.com/ember-weekend/ember-weekend/blob/master/app/adapters/episode.js

iirc this is so we don't end up with a zombie record when we look up by slug.  Though I'd have to look more closely to refresh my memory.

**Comment by toranb** [comment]
Awesome - thanks for the speedy reply @rondale-sc
