### ISSUE TITLE
RSS is outdated

### ISSUE THREAD

**Issue by Serabe** [ember-weekend/ember-weekend#40]
Today, RSS still shows Episode 38 as the last episode (two days after episode 39 was released).
![2015-12-23 at 13 55](https://cloud.githubusercontent.com/assets/36221/11976879/e64d24ae-a97c-11e5-9fe4-5ad4f3ba13bb.png)

**Comment by rondale-sc** [comment]
@serabe I'll see if I can't clear the cache.

**Comment by rondale-sc** [comment]
@Serabe Looks up to date when I go to the site's [rss](https://emberweekend.com/feed.xml).  Is it still incorrect for you?

**Comment by Serabe** [comment]
It is fine now. Thank you!

**Comment by rondale-sc** [comment]
Yay!  Thanks for letting me know @Serabe
